# Generated by Django 3.1.2 on 2020-11-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TF_Question',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Question Vrai/Faux',
                'verbose_name_plural': 'Questions Vrai/Faux',
            },
            bases=('quiz.question',),
        ),
    ]
