# Generated by Django 3.1.2 on 2020-10-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
