# Generated by Django 3.0.2 on 2020-06-18 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz", old_name="subcategory", new_name="sub_category"
        ),
        migrations.AddField(
            model_name="quiz",
            name="creator",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question", name="order", field=models.IntegerField(null=True)
        ),
        migrations.AlterField(
            model_name="quiz",
            name="random_order",
            field=models.BooleanField(
                default=False,
                help_text="Afficher les questions dans l'ordre de création ou aléatoirement ?",
                verbose_name="Ordre aléatoire",
            ),
        ),
    ]
