# Generated by Django 3.0.2 on 2020-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200204_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordered',
            field=models.BooleanField(default=True, help_text="Ordre des questions : aléatoire ou dans l'ordre de création des questions."),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz', verbose_name='Quiz'),
        ),
    ]
