# Generated by Django 3.0.2 on 2020-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200618_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
