# Generated by Django 3.0.2 on 2020-07-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quiz", "0003_auto_20200707_0824")]

    operations = [migrations.RemoveField(model_name="question", name="ordered")]
