# Generated by Django 3.1.2 on 2020-11-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_grade_questionscore_statistic_themescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='score',
            new_name='number',
        ),
    ]
