# Generated by Django 3.1.2 on 2020-10-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('answer1', models.CharField(max_length=1000, verbose_name='Content')),
                ('answer1_correct', models.BooleanField(default=False)),
                ('answer2', models.CharField(max_length=1000, verbose_name='Content')),
                ('answer2_correct', models.BooleanField(default=False)),
                ('answer3', models.CharField(max_length=1000, verbose_name='Content')),
                ('answer3_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Question à choix multiples',
                'verbose_name_plural': 'Questions à choix multiples',
            },
            bases=('quiz.question',),
        ),
    ]
